### ISSUE TITLE
Showing a ??? name

### ISSUE THREAD

**Issue by K0ks337** [sta0003/EngineSimulatorSelector#5]
![image](https://user-images.githubusercontent.com/107277852/187947060-5fd6bc5b-a06b-40f6-84f3-08355b81a250.png)
Explain that

**Comment by K0ks337** [comment]
its working when i change the car so idk the issue

**Comment by sta0003** [comment]
> ![image](https://user-images.githubusercontent.com/107277852/187947060-5fd6bc5b-a06b-40f6-84f3-08355b81a250.png)
> 
> Explain that

Are you able to share the whole engine file?

**Comment by K0ks337** [comment]
yeah 
![image](https://user-images.githubusercontent.com/107277852/188135171-3970f9fb-1ba9-4d64-a459-ff841ab1c1c3.png)
[2jz_vtec.zip](https://github.com/sta0003/EngineSimulatorSelector/files/9477619/2jz_vtec.zip)
it dosent support .mr files or .rar so i upload a .zip file and a photo of this engine and other engines its the 2jz_vtec

**Comment by sta0003** [comment]
Unsupported legacy engines are not supported with this launcher and may appear as odd names.
